services:
  netology_diploma:
    container_name: netology_diploma
    build: ./diploma_pj
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - netology
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netology
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netology -d netology"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - netology
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build:
      context: ./diploma_pj
      dockerfile: Dockerfile.celery
    networks:
      - netology
    depends_on:
      - redis
      - postgres_db
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - netology_diploma
    networks:
      - netology

volumes:
  pgdata:
  static_volume:

networks:
  netology:
