# Generated by Django 5.0.6 on 2024-06-27 10:16

import backend.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.models.UserManager()),
            ],
        ),
    ]
