# Generated by Django 5.0.6 on 2024-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="state",
            field=models.BooleanField(default=True, verbose_name="State of the shop"),
        ),
    ]
