# Generated by Django 5.0.6 on 2024-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_contact_apartment_contact_building_contact_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="family_name",
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("shop", "Shop"), ("buyer", "Buyer")],
                default="buyer",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Phone"),
        ),
    ]
