# Generated by Django 5.0.6 on 2024-06-27 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_remove_user_is_superuser_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
