# Generated by Django 5.0.6 on 2024-07-01 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="apartment",
            field=models.CharField(blank=True, max_length=10, verbose_name="Apartment"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="building",
            field=models.CharField(blank=True, max_length=10, verbose_name="Building"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="City name is not a valid. "
                        "Only letters, spaces, and hyphens are allowed.",
                        regex="^[a-zA-Z\\s-]+$",
                    )
                ],
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="house",
            field=models.CharField(blank=True, max_length=10, verbose_name="House"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="structure",
            field=models.CharField(blank=True, max_length=10, verbose_name="Structure"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
