# Generated by Django 5.0.6 on 2024-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_contact_apartment_alter_contact_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
