# Generated by Django 5.0.6 on 2024-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_confirmemailtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confirmemailtoken",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
