# Generated by Django 5.0.6 on 2024-06-26 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_remove_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="house",
            field=models.CharField(blank=True, max_length=100, verbose_name="House"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: "
                        "'+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(blank=True, max_length=100, verbose_name="Street"),
        ),
    ]
