# Generated by Django 5.0.6 on 2024-07-09 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_confirmemailtoken_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_active",
            new_name="is_email_confirmed",
        ),
    ]
